name: metapype
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - click=8.3.1
  - colorama=0.4.6
  - daiquiri=3.0.0
  - exceptiongroup=1.3.1
  - icu=78.2
  - iniconfig=2.3.0
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.2
  - ncurses=6.5
  - openssl=3.6.0
  - packaging=25.0
  - pip=25.3
  - pluggy=1.6.0
  - pygments=2.19.2
  - pytest=9.0.2
  - python=3.11.14
  - python-json-logger=2.0.7
  - python_abi=3.11
  - readline=8.3
  - rfc3986=2.0.0
  - setuptools=80.9.0
  - tk=8.6.13
  - tomli=2.4.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wheel=0.45.1
  - zstd=1.5.7
prefix: /home/servilla/miniconda3/envs/metapype
